---
name: lint

on:
  [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Stylua
        uses: JohnnyMorganz/stylua-action@v3
        with:
          version: latest
          token: ${{ secrets.GH_TOKEN }}
          args: --check .
